### ISSUE TITLE
Looking glass does not display like it is calibarated and is missing file path

### ISSUE THREAD

**Issue by IanGallacher** [Looking-Glass/BlenderAddOn-Issues#8]
I'm encountering an issue where the edges of the default cube appear fuzzy on the lookingglass display. Additionally, looking at the display head on looks like you are looking from the cube's side, and moving your head from left to right causes the image to "Jump"

I suspect that this might relate to the config extraction utility path is blank. I'm not sure what that is, or whereto find it.

![image](https://user-images.githubusercontent.com/7298650/84212482-daad3700-aa72-11ea-9d3d-1b75bb3b24fb.png)

**Comment by IanGallacher** [comment]
The issue I described above is after pressing ALT + F11 to make it full screen. Is it possible that it is not actually full screen after doing that? I'm on Windows 10, just for reference.

**Comment by alxdncn** [comment]
Wonderful, glad you got this working! Will take a look over the docs to see if there’s a way we can make this clearer - I myself often forget how to get I **fully** full screen and end up with the same artifact you saw.
